import torch
import os

class Config:
    # Dataset Configuration
    NUM_CLASSES = 6  # UCI HAR activities
    INPUT_SIZE = 128  # Window size
    INPUT_FEATURES = 9  # 3x acc + 3x gyro + 3x total_acc
    
    # Federated Learning Parameters
    TOTAL_CLIENTS = 30
    CLIENT_FRACTION = 0.33  # 10/30 clients per round
    ROUNDS = 30
    LOCAL_EPOCHS = 5
    BATCH_SIZE = 16  # Mobile-optimized
    
    # Privacy Requirements (YOUR SPECIFICATIONS)
    EPSILON = 8.0
    DELTA = 1e-5
    MAX_GRAD_NORM = 1.0
    NOISE_MULTIPLIER = 1.2
    
    # Model Requirements (YOUR SPECIFICATIONS)
    TARGET_ACCURACY = 0.95  # >95%
    MAX_MODEL_SIZE_MB = 5   # <5MB
    
    # Training Configuration
    DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    LR = 0.01
    MOMENTUM = 0.9
    WEIGHT_DECAY = 1e-4
    
    # Privacy & Security (YOUR REQUIREMENTS)
    USE_SECURE_AGGREGATION = True
    USE_DIFFERENTIAL_PRIVACY = True
    
    # Paths
    MODEL_SAVE_PATH = "models/"
    
    @classmethod
    def setup_directories(cls):
        os.makedirs("models", exist_ok=True)
        os.makedirs("results", exist_ok=True)

config = Config()
config.setup_directories()
