federated:
  num_rounds: 20
  num_clients: 30
  clients_per_round: 8
  local_epochs: 2
  learning_rate: 0.001
  batch_size: 32
  server_address: "127.0.0.1"
  server_port: 8080
  round_timeout: 60
  client_start_delay: 2.0

model:
  input_size: 561
  hidden_layers: [128, 64]
  num_classes: 6
  dropout_rate: 0.2
  pretrain_path: "models/pretrained/fnn_pretrained.pth"

privacy:
  enable_differential_privacy: true
  noise_multiplier_initial: 0.5      # start noise
  noise_multiplier_final: 0.1        # end noise
  max_grad_norm_initial: 1.0
  max_grad_norm_final: 0.5           # tighter clipping late
  target_epsilon: 10.0
  target_delta: 1e-5
  dp_mechanism: "gaussian"
  account_per_batch: false           # only per round

mobile:
  enable_quantization: true
  enable_pruning: true
  pruning_amount: 0.15
  quantization_backend: "qnnpack"

dataset:
  normalize: true
  test_split: 0.2
  random_seed: 42
  enable_augmentation: true
  augmentation:
    noise_std: 0.05
    rotation_angle: 15
    scaling_factor: [0.9, 1.1]
    time_shift: 5
    augmentation_probability: 0.5
