# Federated Learning and Privacy Configuration

dataset:
  name: UCI_HAR
  num_classes: 6
  input_size: 128
  input_features: 9

federated:
  total_clients: 30
  client_fraction: 0.33      # 10/30 clients per round
  rounds: 30
  local_epochs: 5
  batch_size: 16

privacy:
  epsilon: 8.0
  delta: 1e-5
  max_grad_norm: 1.0
  noise_multiplier: 1.2      # Calibrated for ε & δ

model:
  target_accuracy: 0.95
  max_size_mb: 5
  save_path: models/fl_model.pt

training:
  device: auto               # 'auto' uses GPU if available
  learning_rate: 0.01
  momentum: 0.9
  weight_decay: 1e-4

security:
  use_secure_aggregation: true
  aggregation_noise_scale: 0.1
