import torch

class Config:
    # Dataset
    NUM_CLASSES = 6
    INPUT_SIZE = 128  # Timesteps
    INPUT_FEATURES = 9  # Sensor features
    
    # Federated Learning
    TOTAL_CLIENTS = 30
    CLIENT_FRACTION = 0.33  # 10/30 per round
    ROUNDS = 30
    LOCAL_EPOCHS = 2
    BATCH_SIZE = 32
    
    # Differential Privacy
    EPSILON = 8.0
    DELTA = 1e-5
    MAX_GRAD_NORM = 1.0  # Clipping threshold
    
    # Model
    MODEL_SAVE_PATH = "fl_model.pt"
    TARGET_ACCURACY = 0.95
    MAX_MODEL_SIZE_MB = 5
    
    # Training
    DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    LR = 0.001
    
    # Secure Aggregation
    USE_SECURE_AGGREGATION = True

config = Config()
