# Temporary Hyperparameter Overrides (for experiments)

federated:
  rounds: 30
  local_epochs: 3
  batch_size: 32

training:
  learning_rate: 0.005
  weight_decay: 5e-4

privacy:
  noise_multiplier: 1.0
